# import random
# classes=['12A','12B']
# names = [
#     "John Doe",
#     "Jane Smith",
#     "Michael Brown",
#     "Emily Johnson",
#     "William Davis",
#     "Olivia Martinez",
#     "James Taylor",
#     "Sophia Wilson",
#     "Robert Anderson",
#     "Emma Garcia",
#     "Daniel Hernandez",
#     "Isabella Lopez",
#     "David Martinez",
#     "Mia Thompson",
#     "Joseph Miller",
#     "Ava Robinson",
#     "Charles White",
#     "Charlotte Harris",
#     "Christopher Hall",
#     "Amelia Lee",
#     "Matthew King",
#     "Harper Turner",
#     "Andrew Hill",
#     "Sofia Baker",
#     "William Cooper",
#     "Avery Green",
#     "Anthony Adams",
#     "Scarlett Martinez",
#     "Ryan Carter",
#     "Grace Turner",
#     "Nicholas Wright",
#     "Chloe Martinez",
#     "Alexander Parker",
#     "Penelope Scott",
#     "Benjamin Allen",
#     "Lily Walker",
#     "Samuel Gonzalez",
#     "Victoria Nelson",
#     "Elijah Perez",
#     "Eleanor Mitchell",
#     "Christian Hill",
#     "Hannah Hernandez",
#     "Jackson Perez",
#     "Natalie Davis",
#     "Aiden Mitchell",
#     "Audrey Lewis",
#     "Sebastian Jenkins",
#     "Stella Martinez",
#     "Gabriel Parker",
#     "Lucy Roberts",
#     "Henry Allen",
#     "Savannah Foster",
#     "David Garcia",
#     "Elizabeth Clark",
#     "Carter Young",
#     "Maya Turner",
#     "Owen Lewis",
#     "Layla Allen",
#     "Dylan Davis",
#     "Zoe Perez",
#     "Wyatt King",
#     "Zoey Scott",
#     "Isaac Foster",
#     "Aubrey Turner",
#     "Levi Lopez",
#     "Hannah Adams",
#     "Julian Young",
#     "Aria Lee",
#     "Matthew Mitchell",
#     "Addison Martinez",
#     "Luke Walker",
#     "Ellie Hill",
#     "Christopher Hall",
#     "Lillian Turner",
#     "Joshua Lewis",
#     "Grace Anderson",
#     "Samuel Young",
#     "Scarlett Harris",
#     "Anthony Hernandez",
#     "Sophia Baker",
#     "Charles Foster",
#     "Sofia Thompson",
#     "Daniel Scott",
#     "Abigail King",
#     "Andrew Mitchell",
#     "Harper Williams",
#     "Joseph Clark",
#     "Emily Martinez",
#     "David Walker",
#     "Isabella Hall",
#     "Benjamin Young",
#     "Amelia Lewis",
#     "Michael Smith",
#     "Mia Davis",
#     "William Hill",
#     "Ava Martin",
#     "Christopher Turner",
#     "Charlotte Nelson",
#     "Nicholas Brown",
#     "Olivia Smith"
# ]
# l=[]
# for i,name in enumerate(names):
#     t=(i+100,name,random.choice(classes),random.randint(50,100),random.randint(50,100),random.randint(50,100))
#     l.append(t)
    
# print(
#     'insert into data_1 values',
#     *l,sep=','
# )
